name: Github Hosted Runner
on:
  workflow_dispatch:
jobs:
  #######################################
  # GITHUB(MICROSOFT) HOSTED RUNNERS
  #######################################
  # Github provides hosted runner which runs on micrsoft azure
  #
  github-hosted-ubuntu-vm:
    name: Ubuntu 24.04 VM
    runs-on: ubuntu-24.04
    steps:
      - name: Show runner Info
        run: |
            echo "Hello from ${{ runner.os }}-${{ runner.arch }}"
            echo "Runner name (type): ${{ runner.name }}"
  
  github-hosted-windows-vm:
    name: Windows 2022 VM
    runs-on: windows-2022
    steps:
      - name: show runner info
        shell: pwsh
        run: |
            echo "Hello from ${{ runner.os }}-${{ runner.arch }}"
            echo "Runner name (type): ${{ runner.name }}"
  
  github-hosted-macos-vm:
    name: MacOS 14 VM
    runs-on: macos-14
    steps:
      - name: show runner info
        run: |
            echo "Hello from ${{ runner.os }}-${{ runner.arch }}"
            echo "Runner name (type): ${{ runner.name }}"
        
  alpine-container-on-github-hosted-ubuntu-vm:
    name: Alpine container on Ubuntu VM
    runs-on: ubuntu-24.04
    container:
      image: alpine:3.20
    steps:
      - name: show runner info
        run: |
            echo "Hello from ${{ runner.os }}-${{ runner.arch }}"
            echo "Runner name (type): ${{ runner.name }}"
            echo "Container Image: $(grep PRETTY_NAME /etc/os-release)"